TRAIN_DIR = "./data/Datasets-Covid-MultiClass/train/"
TEST_DIR = "./data/Datasets-Covid-MultiClass/test/"
OUTDIR = "model"
batch_size = 128
crop_size = 224
output_size = 3
    # in_channel = 1
    # conv1 = 8
    # conv2 = 16
    # conv3 = 32
    # conv4 = 64
    # out_channel = 256
    # kernel = 5
    # pad = 2
    # in_size = 256*7*7
    # n1 = 512
    # n2 = 256
    # dropout = 0.15
    # out_size = 3
    # batch_norm = "False"
author = "Ridho Alhafizhi"
